# SPDX-License-Identifier: EUPL-1.2
#
# (C) Copyright 2018-2022 CSI-Piemonte
FROM nivola/nivola-uwsgi

ARG GITUSER=''
ARG GITPWD=''
ARG BRANCH=devel
ARG GITURI=https://$GITUSER:$GITPWD@github.com/Nivola
#ARG GITURI=https://$GITUSER:$GITPWD@github.com/Nivola

ENV GITUSER ${GITUSER}
ENV GITPWD ${GITPWD}

#ARG PYTHONPATH=/usr/local/lib/python3.7/site-packages
ARG PYTHONPATH=/usr/local/uwsgi/pkgs

# copy projects from workspace (instead of doing a git clone from repository)
COPY beecell $PYTHONPATH/beecell/
COPY beedrones/ $PYTHONPATH/beedrones/
COPY beehive/ $PYTHONPATH/beehive/
COPY beehive-oauth2/ $PYTHONPATH/beehive-oauth2/
COPY beehive-resource/ $PYTHONPATH/beehive-resource/
COPY beehive-service/ $PYTHONPATH/beehive-service/
COPY beehive-service-netaas/ $PYTHONPATH/beehive-service-netaas/
COPY beehive-ssh/ $PYTHONPATH/beehive-ssh/

RUN mkdir -p /usr/local/uwsgi/pkgs && \
    chown -R uwsgi:uwsgi /usr/local/uwsgi && \
    # git clone from repository (instead of copying projects from workspace
    #echo "clone from git branch: $BRANCH" && \
    #git clone -b $BRANCH $GITURI/cmp3/beecell.git $PYTHONPATH/beecell && \
    #git clone -b $BRANCH $GITURI/cmp2/beedrones.git $PYTHONPATH/beedrones && \
    #git clone -b $BRANCH $GITURI/cmp2/beehive.git $PYTHONPATH/beehive && \
    #git clone -b $BRANCH $GITURI/cmp2/beehive-service.git $PYTHONPATH/beehive-service && \
    #git clone -b $BRANCH $GITURI/cmp3/beehive-service-netaas.git $PYTHONPATH/beehive-service-netaas && \
    #git clone -b $BRANCH $GITURI/cmp2/beehive-resource.git $PYTHONPATH/beehive-resource && \
    #git clone -b $BRANCH $GITURI/cmp2/beehive-ssh.git $PYTHONPATH/beehive-ssh && \
    #git clone -b $BRANCH $GITURI/cmp2/beehive-oauth2.git $PYTHONPATH/beehive-oauth2 && \
    echo "install requirements from MANIFEST" && \
    cd $PYTHONPATH && pip3 install -r beecell/MANIFEST.md  && \
    cd $PYTHONPATH && pip3 install -r beedrones/MANIFEST.md  && \
    cd $PYTHONPATH && pip3 install -r beehive/MANIFEST.md  && \
    cd $PYTHONPATH && pip3 install -r beehive-oauth2/MANIFEST.md  && \
    cd $PYTHONPATH && pip3 install -r beehive-service/MANIFEST.md  && \
    cd $PYTHONPATH && pip3 install -r beehive-service-netaas/MANIFEST.md  && \
    cd $PYTHONPATH && pip3 install -r beehive-resource/MANIFEST.md  && \
    cd $PYTHONPATH && pip3 install -r beehive-ssh/MANIFEST.md
    #echo "install projects for testing setup" && \
    #cd $PYTHONPATH && pip3 install beecell/  && \
    #cd $PYTHONPATH && pip3 install beedrones/  && \
    #cd $PYTHONPATH && pip3 install beehive/  && \
    #cd $PYTHONPATH && pip3 install beehive-oauth2/  && \
    #cd $PYTHONPATH && pip3 install beehive-service/  && \
    #cd $PYTHONPATH && pip3 install beehive-service-netaas/  && \
    #cd $PYTHONPATH && pip3 install beehive-resource/  && \
    #cd $PYTHONPATH && pip3 install beehive-ssh/
    pip3 install uWSGI==2.0.20
    
# uncomment if you don't install projects
ENV PYTHONPATH $PYTHONPATH/beehive:$PYTHONPATH/beecell:$PYTHONPATH/beedrones:$PYTHONPATH/beehive-oauth2:\
$PYTHONPATH/beehive-service:$PYTHONPATH/beehive-service-netaas:$PYTHONPATH/beehive-resource:$PYTHONPATH/beehive-ssh

WORKDIR /usr/local/uwsgi
USER uwsgi:uwsgi
#EXPOSE 8070
#EXPOSE 8080
EXPOSE 9191

CMD [ "uwsgi", "/etc/uwsgi/uwsgi.ini"]
