# SPDX-License-Identifier: GPL-3.0-or-later
#
# (C) Copyright 2018-2019 CSI-Piemonte
# (C) Copyright 2019-2020 CSI-Piemonte
# (C) Copyright 2020-2021 CSI-Piemonte
#namePrefix: local-
commonLabels:
  environment: mylab
namespace: beehive-mylab
bases:
  - ../base
#resources:
#  - nginx.yml
configMapGenerator:
#- name: haproxy-config
#  files:
#  - _res/haproxy-mariadb.cfg
- name: proxysql-configmap
  files:
  - _res/proxysql.cnf
- name: redis-configmap
  files:
  -  _res/redis.cnf
- name: nginx-config
  files:
  - _res/nginx.cnf
#- name: nginx-certificate-config
#  files:
#  - _res/nginx.crt
#  - _res/nginx.key