# SPDX-License-Identifier: EUPL-1.2
#
# (C) Copyright 2018-2022 CSI-Piemonte
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    name: lb
  namespace: beehive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2
        imagePullPolicy: Always
        # command: ["uwsgi", "--yaml", "/etc/uwsgi/uwsgi.yaml"]
        ports:
          - containerPort: 80
            name: nginx-http
          - containerPort: 443
            name: nginx-https
        volumeMounts:
          - name: nginx-config-vol
            mountPath: /etc/nginx/conf.d/mylab.conf
            subPath: nginx.cnf
          - name: nginx-certificate-vol
            mountPath: /etc/nginx/ssl/nginx.crt
            subPath: nginx.crt
          - name: nginx-certificate-vol
            mountPath: /etc/nginx/ssl/nginx.key
            subPath: nginx.key
      volumes:
        - name: nginx-config-vol
          configMap:
            name: nginx-config
        - name: nginx-certificate-vol
          configMap:
            name: nginx-certificate-config

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
      name: nginx-http
    - port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 30443
      name: nginx-https
  selector:
    app: nginx-pod