# SPDX-License-Identifier: EUPL-1.2
#
# (C) Copyright 2018-2022 CSI-Piemonte
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: frontend
    spec:
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 30
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 30
#      restartPolicy: Always
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - rabbitmq-hard
#            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: rabbitmq:3.8.5-management
        name: rabbitmq
        ports:
        - containerPort: 5672
          name: rabbitmq-amqp
        env:
          - name: TZ
            value: Europe/Rome
          - name: RABBITMQ_DEFAULT_USER
            value: beehive
          - name: RABBITMQ_DEFAULT_PASS
            value: EKbK8yQ7q05N
          - name: RABBITMQ_DEFAULT_VHOST
            value: nivola
#        ports:
#        - containerPort: 6033
#          name: rabbitmq-mysql
#        - containerPort: 6032
#          name: rabbitmq-admin
#        - containerPort: 6080
#          name: rabbitmq-stats

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: rabbitmq-amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: rabbitmq-mgmt-console
  selector:
    app: rabbitmq