apiVersion: v1
kind: PersistentVolume
metadata:
  name: beehive-volume
  labels:
    type: local
  namespace: beehive
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: <WORKSPACE>

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beehive-volume-claim
  namespace: beehive
spec:
  storageClassName: manual
  volumeName: beehive-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi