# SPDX-License-Identifier: GPL-3.0-or-later
#
# (C) Copyright 2018-2019 CSI-Piemonte
# (C) Copyright 2019-2020 CSI-Piemonte
# (C) Copyright 2020-2021 CSI-Piemonte
apiVersion: v1
kind: PersistentVolume
metadata:
  name: beehive-volume
  labels:
    type: local
  namespace: beehive
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    # if you start minikube with --driver=docker
    # (mount your workspace passing to minikube --mount=true --mount-string="<WORKSPACE>:/pkgs")
    path: /pkgs
    # if you start minikube with --driver=none
    #path: <WORKSPACE>
    

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beehive-volume-claim
  namespace: beehive
spec:
  storageClassName: manual
  volumeName: beehive-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi