# SPDX-License-Identifier: GPL-3.0-or-later
#
# (C) Copyright 2018-2019 CSI-Piemonte
# (C) Copyright 2019-2020 CSI-Piemonte
# (C) Copyright 2020-2021 CSI-Piemonte
apiVersion: v1
kind: Namespace
metadata:
  name: beehive-mylab
  labels:
    name: beehive-mylab