# SPDX-License-Identifier: GPL-3.0-or-later
#
# (C) Copyright 2018-2022 CSI-Piemonte
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tmp-volume
  labels:
    type: local
  namespace: beehive
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/logs"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tmp-volume-claim
  namespace: beehive
spec:
  storageClassName: manual
  volumeName: tmp-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi