apiVersion: v1
data:
  API_CATALOG: beehive-internal
  API_ENV: mylab
  API_FERNET_KEY: wwN8462BS0RQCfBeREcCL6UGuUNbsUpZu7eAHuxzu4M=
  API_LOG: /tmp/
  API_OAUTH2_CLIENT: 3475f193-8de6-49b9-9b37-12aed6d69cd1:0nEkYztgADWcx7iIz8CNlBuSljTJDAyfqU24YvGi
  API_PREFIX: ""
  API_TIMEOUT: "60"
  CELERY_BROKER_URI: amqp://beehive:EKbK8yQ7q05N@$(RABBITMQ_SERVICE_HOST):5672/nivola
  ELASTIC_NODES: dev-beehive-07.tstsddc.csi.it
  GEVENT_NUMBER: "200"
  LOGGING_LEVEL: "10"
  LOGSTASH: ""
  LOGSTASH_CA: ""
  LOGSTASH_CERT: ""
  LOGSTASH_PKEY: ""
  MAIL_SENDER: sergio.tonani@csi.it
  MAIL_SERVER: mailfarm-app.csi.it
  MYSQL_URI: mysql+pymysql://event:event@dev-beehive-07.tstsddc.csi.it:3306/event
  OAUTH2_ENDPOINT: https://dev-beehive-07.tstsddc.csi.it
  PYTHONBASEPATH: /usr/local/lib/python3.7/site-packages
  REDIS_IDENTITY_URI: redis://:t5vo5ChFCCe8I1toguvOFXFUW1jU9WSJr4H13aNiOAV@$(REDIS_SERVICE_HOST):6379/0
  REDIS_QUEUE_URI: redis://:t5vo5ChFCCe8I1toguvOFXFUW1jU9WSJr4H13aNiOAV@$(REDIS_SERVICE_HOST):6379/0
  REDIS_URI: redis://:t5vo5ChFCCe8I1toguvOFXFUW1jU9WSJr4H13aNiOAV@$(REDIS_SERVICE_HOST):6379/0
  SYSLOG_SERVER: ""
  TASK_EXPIRE: "86400"
  TASK_TIME_LIMIT: "1200"
kind: ConfigMap
metadata:
  labels:
    environment: mylab
  name: env-config-826ddkbk92
  namespace: beehive-mylab
---
apiVersion: v1
data:
  uwsgi-event.yml: |
    # SPDX-License-Identifier: GPL-3.0-or-later
    #
    # (C) Copyright 2018-2019 CSI-Piemonte
    # (C) Copyright 2019-2020 CSI-Piemonte

    uwsgi:
        api_id: event
        api_name: beehive
        api_subsystem: event
        api_package: beehive
        api_env: $(API_ENV)
        api_pod: $(API_POD)
        api_prefix: $(API_PREFIX)
        api_fernet_key: $(API_FERNET_KEY)
        api_host: $(API_POD_IP)
        api_fqdn: $(API_POD_IP)
        api_catalog: $(API_CATALOG)
        api_endpoint: $(API_ENDPOINT)
        api_oauth2_client: $(API_OAUTH2_CLIENT)
        api_cluster_ip: $(API_CLUSTER_IP)
        api_timeout: $(API_TIMEOUT)
        api_log: $(API_LOG)
        api_swagger_spec_path: /usr/local/uwsgi/pkgs/beehive/beehive/server/swagger.yml
        api_logging_level: $(LOGGING_LEVEL)

        # socket configuration uwsgi, http
        socket: :8071
        http-socket: :8081

        # startup user
        uid: uwsgi
        gid: uwsgi

        # daemon configuration
        #daemonize: /tmp/event-01.api.out
        #pidfile: /tmp/event-01.pid
        #vacuum: true

        # python configuration
        #virtualenv: %d../../
        plugins: python3,gevent_python3
        py-programname: python3

        # process configuration
        # master: true
        enable-threads: true
        # workers: 1
        gevent: $(GEVENT_NUMBER)
        gevent-monkey-patch: true
        #procname: event
        # cpu-affinity: 1

        # queue configuration
        #queue: 10
        #queue-blocksize: 64000

        #cache2: name=portal_cache,items=100

        # app configuration
        module: beehive.server.api:app

        oauth2_endpoint: $(OAUTH2_ENDPOINT)

        # database uri
        database_uri: $(MYSQL_URI)

        # redis uri
        redis_identity_uri: $(REDIS_IDENTITY_URI)
        redis_uri: $(REDIS_URI)
        redis_queue_uri: $(REDIS_QUEUE_URI)
        redis_celery_uri: $(REDIS_QUEUE_URI)

        # elasticsearch nodes
        elasticsearch_nodes: $(ELASTIC_NODES)

        # logstash configuration
        logstash_host: $(LOGSTASH)
        logstash_ca: $(LOGSTASH_CA)
        logstash_cert: $(LOGSTASH_CERT)
        logstash_pkey: $(LOGSTASH_PKEY)

        # sendmail
        sendmail_server: $(MAIL_SERVER)
        sendmail_sender: $(MAIL_SENDER)

        # task manager / scheduler
        # broker_url: $(REDIS_QUEUE_URI)
        broker_url: $(CELERY_BROKER_URI)
        broker_queue: celery.event.$(API_ENV)
        broker_queue_event: celery.event.$(API_ENV)
        broker_queue_catalog: celery.catalog.$(API_ENV)
        result_backend: $(REDIS_QUEUE_URI)
        expire: $(TASK_EXPIRE)
        task_time_limit: $(TASK_TIME_LIMIT)

        # syslog server
        syslog_server: $(SYSLOG_SERVER)

        # task modules
        task_module: 1
        task_module.1: beehive.module.catalog.tasks_v2

        # api modules
        api_module: 3
        api_module.1: beehive.module.basic.mod.BasicModule
        api_module.2: beehive.module.event.mod.EventModule,true
        api_module.3: beehive.module.scheduler_v2.mod.SchedulerModuleV2

        # api plugins
        # api_plugin: 0

        # event handler
        event_handler: 2
        event_handler.1: beehive.module.auth.event.AuthEventHandler
        event_handler.2: beehive.module.event.handler_cli.CliEventHandler

        # api plugins
        # api_plugin: 0

        # event handler
        # event_handler: 0
kind: ConfigMap
metadata:
  labels:
    environment: mylab
  name: event-config-kgkt2bfc87
  namespace: beehive-mylab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: mylab
    name: event
    role: beat
  name: beat-event-app
  namespace: beehive-mylab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat-event-pod
      environment: mylab
  template:
    metadata:
      labels:
        app: beat-event-pod
        environment: mylab
    spec:
      containers:
      - command:
        - /usr/local/uwsgi/pkgs/beehive/beehive/server/scheduler_v2.py
        - /etc/uwsgi/uwsgi.yaml
        - 2>&1
        - '>/tmp/event.beat.log'
        env:
        - name: TZ
          value: Europe/Rome
        - name: API_CLUSTER_IP
          value: $(UWSGI_EVENT_CLUSTERIP_SERVICE_HOST)
        - name: API_ENDPOINT
          value: http://$(UWSGI_AUTH_CLUSTERIP_SERVICE_HOST):8080
        - name: API_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: env-config-826ddkbk92
        image: docker-nivola.ecosis.csi.it/nivola-cmp:prova_lib_updated
        imagePullPolicy: Always
        name: beat-event
        volumeMounts:
        - mountPath: /tmp
          name: beat-tmp-volume
        - mountPath: /usr/local/uwsgi/pkgs
          name: beat-beehive-volume
        - mountPath: /etc/uwsgi/uwsgi.yaml
          name: uwsgi-config
          subPath: uwsgi-event.yml
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      volumes:
      - name: beat-tmp-volume
        persistentVolumeClaim:
          claimName: tmp-volume-claim
      - name: beat-beehive-volume
        persistentVolumeClaim:
          claimName: beehive-volume-claim
      - configMap:
          name: event-config-kgkt2bfc87
        name: uwsgi-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: mylab
    name: event
    role: consumer
  name: consumer-event-app
  namespace: beehive-mylab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-event-pod
      environment: mylab
  template:
    metadata:
      labels:
        app: consumer-event-pod
        environment: mylab
    spec:
      containers:
      - command:
        - /usr/local/uwsgi/pkgs/beehive/beehive/server/event_v2.py
        - /etc/uwsgi/uwsgi.yaml
        - 2>&1
        - '>/tmp/event.consumer.log'
        env:
        - name: TZ
          value: Europe/Rome
        - name: API_CLUSTER_IP
          value: $(UWSGI_EVENT_CLUSTERIP_SERVICE_HOST)
        - name: API_ENDPOINT
          value: http://$(UWSGI_AUTH_CLUSTERIP_SERVICE_HOST):8080
        - name: API_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: env-config-826ddkbk92
        image: docker-nivola.ecosis.csi.it/nivola-cmp:prova_lib_updated
        imagePullPolicy: Always
        name: consumer-event
        volumeMounts:
        - mountPath: /tmp
          name: consumer-tmp-volume
        - mountPath: /usr/local/uwsgi/pkgs
          name: consumer-beehive-volume
        - mountPath: /etc/uwsgi/uwsgi.yaml
          name: uwsgi-config
          subPath: uwsgi-event.yml
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      volumes:
      - name: consumer-tmp-volume
        persistentVolumeClaim:
          claimName: tmp-volume-claim
      - name: consumer-beehive-volume
        persistentVolumeClaim:
          claimName: beehive-volume-claim
      - configMap:
          name: event-config-kgkt2bfc87
        name: uwsgi-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: mylab
    name: event
    role: uwsgi
  name: uwsgi-event-app
  namespace: beehive-mylab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uwsgi-event-pod
      environment: mylab
  template:
    metadata:
      labels:
        app: uwsgi-event-pod
        environment: mylab
    spec:
      containers:
      - command:
        - uwsgi
        - --yaml
        - /etc/uwsgi/uwsgi.yaml
        env:
        - name: TZ
          value: Europe/Rome
        - name: API_CLUSTER_IP
          value: $(UWSGI_EVENT_CLUSTERIP_SERVICE_HOST)
        - name: API_ENDPOINT
          value: http://$(UWSGI_AUTH_CLUSTERIP_SERVICE_HOST):8080
        - name: API_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: env-config-826ddkbk92
        image: docker-nivola.ecosis.csi.it/nivola-cmp:prova_lib_updated
        imagePullPolicy: Always
        name: uwsgi-event
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /tmp
          name: uwsgi-tmp-volume
        - mountPath: /usr/local/uwsgi/pkgs
          name: uwsgi-beehive-volume
        - mountPath: /etc/uwsgi/uwsgi.yaml
          name: uwsgi-config
          subPath: uwsgi-event.yml
      volumes:
      - name: uwsgi-tmp-volume
        persistentVolumeClaim:
          claimName: tmp-volume-claim
      - name: uwsgi-beehive-volume
        persistentVolumeClaim:
          claimName: beehive-volume-claim
      - configMap:
          name: event-config-kgkt2bfc87
        name: uwsgi-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: mylab
    name: event
    role: worker
  name: worker-event-app
  namespace: beehive-mylab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-event-pod
      environment: mylab
  template:
    metadata:
      labels:
        app: worker-event-pod
        environment: mylab
    spec:
      containers:
      - command:
        - /usr/local/uwsgi/pkgs/beehive/beehive/server/task_v2.py
        - /etc/uwsgi/uwsgi.yaml
        - 2>&1
        - '>/tmp/event.worker.log'
        env:
        - name: TZ
          value: Europe/Rome
        - name: API_CLUSTER_IP
          value: $(UWSGI_EVENT_CLUSTERIP_SERVICE_HOST)
        - name: API_ENDPOINT
          value: http://$(UWSGI_AUTH_CLUSTERIP_SERVICE_HOST):8080
        - name: API_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: env-config-826ddkbk92
        image: docker-nivola.ecosis.csi.it/nivola-cmp:prova_lib_updated
        imagePullPolicy: Always
        name: worker-event
        volumeMounts:
        - mountPath: /tmp
          name: worker-tmp-volume
        - mountPath: /usr/local/uwsgi/pkgs
          name: worker-beehive-volume
        - mountPath: /etc/uwsgi/uwsgi.yaml
          name: uwsgi-config
          subPath: uwsgi-event.yml
      volumes:
      - name: worker-tmp-volume
        persistentVolumeClaim:
          claimName: tmp-volume-claim
      - name: worker-beehive-volume
        persistentVolumeClaim:
          claimName: beehive-volume-claim
      - configMap:
          name: event-config-kgkt2bfc87
        name: uwsgi-config
